### ISSUE TITLE
scramble questions in 10 datasets

### ISSUE THREAD

**Issue by hckum** [pinformatics/MINDFIRL-userstudy#12]
Make sure to put one attention question per page

**Comment by ilangurudev** [comment]
@hckum Please confirm if satisfactory and if yes, please close the issue.

**Comment by hckum** [comment]
I reviewed the scrambled questions, and realized we need a more structured scrambling, like one easy quesiton per page, but for other question types too.

So I looked at the exactly question types, so we can random sample at most one question from the same question type per page. I will email you on this separately.
