### ISSUE TITLE
Section 2 sampling

### ISSUE THREAD

**Issue by ilangurudev** [pinformatics/MINDFIRL-userstudy#28]

**Comment by ilangurudev** [comment]
[samples folder](https://github.com/Turmac/MINDFIRL/tree/ustudy5_V2/ppirl-userstudy/data/pipeline/data_output/samples_sections_scrambling)

**Comment by hckum** [comment]
Guru, I checked everything carefully looking at the raw CSV file.
Great Job! Exactly what I was thinking and quite complicated but done well.

**Comment by ilangurudev** [comment]
Repeats present
