### ISSUE TITLE
Open all cells on submission

### ISSUE THREAD

**Issue by ilangurudev** [pinformatics/MINDFIRL-userstudy#30]

**Comment by Turmac** [comment]
This is done on section 1. The logic is following:
1. file: app.py, function: feedback_main_section
on server side, the function "feedback_main_section" generate the data table for full mode.
2. file: form_submit_mod.js, function: submit_grade
    a. replace the data table
    b. remove everything clickable
    c. resume the choice panel

Guru, please check this and do the similar thing in tutorial.

**Comment by ilangurudev** [comment]
Qinbo, can you do it? I don't understand the working!

**Comment by Turmac** [comment]
Okay, I will work on this, but in general we should work on our own files.
Which url need this function?
tutorial/privacy/practice, practice 2, no clickable, mask mode
tutorial/clickable/demo, a demo page for clickable interface (this page has no feedback?)
tutorial/clickable/decision_making_demo, a demo page for clickable interface
tutorial/clickable/practice, practice 3, clickable, meter, limit

**Comment by ilangurudev** [comment]
I think I get it now. Will try to tc, thanks. Will ask if I am facing probs.

**Comment by ilangurudev** [comment]
Okay done.
