### ISSUE TITLE
Different CSSs for tutorial and main section?

### ISSUE THREAD

**Issue by ilangurudev** [pinformatics/MINDFIRL-userstudy#34]
@Turmac I noticed that the tutorial and main section use different formatting rules?! Asking because I tried to align the wrong icon in the main section but the alignment got messed up in the tutorial! Seeing this for the icons as well - The big icons get aligned pretty well in the main section but not in tutorial. I thought they were using the same functions from data_display.py to render? (I copied your the tutorial sections you had initially when I redid the section).

**Comment by Turmac** [comment]
Everywhere is using the same formatting rules. The data is formatted when creating the DataPairList object, so they are the same. Which url has the problem? (maybe check the css file to see if they are the same? All the style for data table are in style.css)
