### ISSUE TITLE
all main study pages should fit in one page no scroll bar

### ISSUE THREAD

**Issue by hckum** [pinformatics/MINDFIRL-userstudy#36]
@Turmac 
I just checked what you did on this, and the scroll bar is still there, especially when we hit submit and a sentence comes in.

please make it fit all on one page. Suggestions
* make the title smaller (we had it miuch smaller before. maybe even 20pt)
* make the button height half of what it is (you can still keep text size the same)

**Comment by Turmac** [comment]
Done. Title is smaller. Footer is removed in main section.
