### ISSUE TITLE
Data collection

### ISSUE THREAD

**Issue by Turmac** [pinformatics/MINDFIRL-userstudy#4]
1. Redesign data collection - Qinbo
2. Data analysis - Guru

**Comment by Turmac** [comment]
1. add data display mode
2. main section start time

**Comment by ilangurudev** [comment]
1. Add Mode
2. Good to have the cell ids for kapr values
3. Standardize timestamp

**Comment by Turmac** [comment]
These features are done. Please check and close data collection.

**Comment by ilangurudev** [comment]
@Turmac 

1. Tried doing the study many times over to enable new data collection.
1. Copy - pasted the newly generated data into a file 
1. Tried running raw2csv,py but ran into an error. 
![error](https://user-images.githubusercontent.com/20581414/37509454-661672de-28c5-11e8-8772-3ae41e08a82d.png)

**Comment by ilangurudev** [comment]
Please include the raw file/csv file that I need to test

**Comment by Turmac** [comment]
fixed. use /flashdb to clear the old data, then collect the new data.

**Comment by ilangurudev** [comment]
![screenshot-20180319111626-661x414](https://user-images.githubusercontent.com/20581414/37607809-065533c2-2b67-11e8-81b3-fa05a1275fd2.png)

**Comment by ilangurudev** [comment]
Qinbo, can you please generate the csv? I will take it from there.. I think it's easier for you to debug and run and get the csv than me trying to do it.

**Comment by Turmac** [comment]
I noticed something like this in user data:
uid:15,user in url: /tutorial/privacy/practice;

this is from the javascript in old html file.
If we are collection user data in tutorial, please follow this format:

must have: uid, type, value, timestamp
the format of key-value pair is 'key:value'
the key-value pair is separated by ','
each piece of data is separated by ';'

**Comment by ilangurudev** [comment]
For the same id, we have multiple modes. Is this okay?
![screenshot-20180319232538-742x244](https://user-images.githubusercontent.com/20581414/37635953-dd13bafe-2bcc-11e8-9bf0-c9d49b27bb7e.png)

**Comment by ilangurudev** [comment]
I don't understand why this happens though. Not sure if it might cause problems later on! For 1 id, we have 2 modes and hence 2 disclosure scores for the same section.

And because of this, we cannot calculate the score for a uid-mode combo becuase the final-answer does not have the mode information. 

Except this we have everything we need.

**Comment by ilangurudev** [comment]
If Dr. Kum feels that there won't be any such problems in the user study because we have a strict cntrol over the id assignments through url, then we can go ahead and close this issue and I can deploy and test.

**Comment by hckum** [comment]
Qinbo, please add in mode

**Comment by Turmac** [comment]
mode added.

**Comment by ilangurudev** [comment]
Mode is extractable now. Thanks.

**Comment by ilangurudev** [comment]
Only one thing left: How does uid 2004 have 42 questions?
