### ISSUE TITLE
Refine pre/post survey

### ISSUE THREAD

**Issue by Turmac** [pinformatics/MINDFIRL-userstudy#8]

**Comment by ilangurudev** [comment]
pre_survey done

**Comment by hckum** [comment]
Is this the first time you have seen such an interface for record linkage?

**Comment by ilangurudev** [comment]
![pre_survey](https://user-images.githubusercontent.com/20581414/37928276-f34cdd8e-3101-11e8-9d4d-89be0f8ffab0.png)

@hckum  Removed the occupation. Still having current degree, highest degree and dept on. 

Thoughts?

**Comment by hckum** [comment]
@ilangurudev 
The question we discussed as the last three in post survey. how about

Assume that researchers were given permission to use personal health information to link from multiple hospitals using personally identifing information (e.g., names, dob, ssn etc) using the kinds of software you just used. You just found out that they also had your information. Answer the following questions.

"1. How comfortable are you to give permission to researchers to use your personal health information to link from multiple databases using your personally identifing information (e.g., names, dob, ssn etc) knowing how they would access your data ?"

options:
1=very uncomfortable, 
2=somewhat uncomfortable 
3= okay to give permission
4=somewhat comfortable, 
5= very comfortable 

(the rest are open ended questions)
2. Are there things you like about the software that would be useful to communicate to subjects of the data ?

3. What things are you concerned about that would be useful to communicate to subjects of the data?

4: What other information about the software or how it was used would you like to know?
